name: atlas_dashboard
description: "ATLAS Dashboard"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated for modern Dart/Flutter

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.5

  # Firebase
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0

  # Utilities
  equatable: ^2.0.5
  intl: ^0.19.0

  # UI & Charting
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0         # For historical line charts
  percent_indicator: ^4.2.3 # For battery, memory, storage gauges
  cupertino_icons: ^1.0.8

  flutter_map: ^8.0.2  # For the map
  latlong2: ^0.9.1
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true